/**
 * LTspice netlist export (.net).
 *
 * Derived from the schematic module's SPICE netlist, which is already
 * LTspice-compatible in structure: voltage-controlled-switch subckts with
 * Ron/Roff SW models, PULSE gate sources, a `.tran` directive and `.end`
 * termination. This module adds an LTspice-friendly comment header,
 * sanitizes node names (no spaces or characters LTspice chokes on) and
 * guarantees the `.tran`/`.end` directives are present, in that order.
 * No `.backanno` (that is a schematic-capture artifact, not for raw
 * netlists). Output is deterministic.
 */

import type { Schematic } from "@/lib/types";

/** LTspice node names: alphanumerics plus `_ + - .` — everything else → `_`. */
const sanitizeNode = (net: string): string => net.replace(/[^A-Za-z0-9_+.-]/g, "_");

const escapeRe = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * Produce an LTspice-flavored netlist for a Schematic. `title` becomes the
 * leading comment line (LTspice treats the first line as the title).
 */
export function ltspiceNetlist(sch: Schematic, title: string): string {
  const cleanTitle = title.replace(/\s+/g, " ").trim();

  // Net-name sanitization map, applied longest-name-first so a spaced net
  // like "NET A" is rewritten before any shorter overlapping name.
  const renames = sch.nets
    .map((n) => [n, sanitizeNode(n)] as const)
    .filter(([from, to]) => from !== to)
    .sort((a, b) => b[0].length - a[0].length);

  const body: string[] = [];
  for (const line of sch.spiceNetlist.split(/\r?\n/)) {
    if (!line.trim()) continue;
    if (line.trimStart().startsWith("*")) {
      body.push(line);
      continue;
    }
    let out = line;
    for (const [from, to] of renames) {
      out = out.replace(new RegExp(`(^|[\\s(,=])${escapeRe(from)}(?=$|[\\s),])`, "g"), `$1${to}`);
    }
    body.push(out);
  }

  // Guarantee .tran exists and .end terminates the deck exactly once.
  const hasTran = body.some((l) => l.trim().toLowerCase().startsWith(".tran"));
  const endIdx = body.findIndex((l) => l.trim().toLowerCase() === ".end");
  if (endIdx >= 0) body.splice(endIdx);
  if (!hasTran) body.push(".tran 1e-6 2e-3");
  body.push(".end");

  const header = [
    `* ${cleanTitle} — LTspice netlist`,
    "* Generated by VoltForge (deterministic export). Switches are voltage-controlled",
    "* SW subckts with Ron/Roff; gates are PULSE-driven; net PGND is node 0.",
  ];
  return [...header, ...body].join("\n") + "\n";
}
